name: Build Magma Access Gateway Docker Images for ARM

on: [push]

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
    - uses: AutoModality/action-clean@v1
    - name: Build AGW Docker images for ARM
      run: |
        ls
        git clone https://github.com/m-govind/magma.git
        pwd
        ls
