name: docker build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
    - name: Build AGW Docker images for ARM
      run: |
        echo "Hello World"
