name: Build Magma Access Gateway Docker Images for ARM

on: [push]

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
    - name: Cleanup
      run: rm -rf *
    - name: Build AGW Docker images for ARM
      run: |
        ls
        git clone https://github.com/m-govind/magma.git
        pwd
        ls
